name: Deploy an old version of MFTC
run-name: ${{ github.actor }} deploying old version of MFTC
on:
  push:
    branches:
      - 'main'
jobs:
  Deploy-old-MFTC-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v4
      - name: save mftc version we want to use
        run: |
          echo "mftc_version=$(cat mftc-version.txt)" >> "$GITHUB_ENV"
      - name: enable corepack
        run: corepack enable
      - name: create an empty branch
        run: git switch --orphan mftc-main
      - name: fetch the version of mftc we want
        run: git fetch https://github.com/emcee5601/fit-test-console.git "${mftc_version}"
      - name: materialize files
        run: git checkout FETCH_HEAD
      - name: install deps
        run: yarn install
      - name: build
        run: yarn build
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
